services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: prestamos-facil-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle_pass
      APP_USER: prestamos_user
      APP_USER_PASSWORD: prestamos_pass
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  rabbitmq:
    image: rabbitmq:management
    container_name: prestamos-facil-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mailpit:
    image: axllent/mailpit
    container_name: prestamos-facil-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  oracle_data:
