<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <groupId>com.prestamosfacil</groupId>
    <artifactId>prestamos-facil-api</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>prestamos-facil-api</name>
    <description>Prestamos Facil API</description>

    <properties>
        <java.version>25</java.version>
    </properties>

    <modules>
        <module>domain/models</module>
        <module>applications/use-cases</module>
        <module>infrastructure/driven-adapters/oracle-adapter</module>
        <module>infrastructure/driven-adapters/rabbitmq-adapter</module>
        <module>infrastructure/driven-adapters/redis-adapter</module>
        <module>infrastructure/entry-points</module>
    </modules>
</project>